-- MySQL Script generated by MySQL Workbench
-- Sun Mar  7 19:51:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PRESENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRESENTE` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AMIGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AMIGO` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESENTE_has_AMIGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRESENTE_has_AMIGO` (
  `PRESENTE_codigo` INT NOT NULL,
  `AMIGO_codigo` INT NOT NULL,
  `dataDeEntrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRESENTE_codigo`, `AMIGO_codigo`),
  INDEX `fk_PRESENTE_has_AMIGO_AMIGO1_idx` (`AMIGO_codigo` ASC) VISIBLE,
  INDEX `fk_PRESENTE_has_AMIGO_PRESENTE_idx` (`PRESENTE_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_PRESENTE_has_AMIGO_PRESENTE`
    FOREIGN KEY (`PRESENTE_codigo`)
    REFERENCES `mydb`.`PRESENTE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRESENTE_has_AMIGO_AMIGO1`
    FOREIGN KEY (`AMIGO_codigo`)
    REFERENCES `mydb`.`AMIGO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
